//定义信令检索的三个查询状态   actiontypes
export const LOAD_TOPOLOGY = 'LOAD_TOPOLOGY';
export const LOAD_TOPOLOGY_SUCCESS = 'LOAD_TOPOLOGY_SUCCESS';
export const LOAD_TOPOLOGY_ERROR = 'LOAD_TOPOLOGY_ERROR';

export const LOAD_COMMUNICATION = 'LOAD_COMMUNICATION';
export const LOAD_COMMUNICATION_SUCCESS = 'LOAD_COMMUNICATION_SUCCESS';
export const LOAD_COMMUNICATION_ERROR = 'LOAD_COMMUNICATION_ERROR';
