//定义信令检索的三个查询状态   actiontypes
export const LOAD_SIGNALLING = 'LOAD_SIGNALLING';
export const LOAD_SIGNALLING_SUCCESS = 'LOAD_SIGNALLING_SUCCESS';
export const LOAD_SIGNALLING_ERROR = 'LOAD_SIGNALLING_ERROR';

export const LOAD_DETAIL = 'LOAD_DETAIL';
export const LOAD_DETAIL_SUCCESS = 'LOAD_DETAIL_SUCCESS';
export const LOAD_DETAIL_ERROR = 'LOAD_DETAIL_ERROR';
export const CLOSE_DETAIL = 'CLOSE_DETAIL'
