export const LOAD_PIECHART = 'LOAD_PIECHART';
export const LOAD_PIECHART_SUCCESS = 'LOAD_PIECHART_SUCCESS';
export const LOAD_PIECHART_ERROR = 'LOAD_PIECHART_ERROR';

export const LOAD_SIGNLIST = 'LOAD_SIGNLIST';
export const LOAD_SIGNLIST_SUCCESS = 'LOAD_SIGNLIST_SUCCESS';
export const LOAD_SIGNLIST_ERROR = 'LOAD_SIGNLIST_ERROR';

export const LOAD_LINECHART = 'LOAD_LINECHART';
export const LOAD_LINECHART_SUCCESS = 'LOAD_LINECHART_SUCCESS';
export const LOAD_LINECHART_ERROR = 'LOAD_LINECHART_ERROR';

export const LOAD_LINETOP = 'LOAD_LINETOP';
export const LOAD_LINETOP_SUCCESS = 'LOAD_LINETOP_SUCCESS';
export const LOAD_LINETOP_ERROR = 'LOAD_LINETOP_ERROR';

export const LOAD_ANALAZYDATA = 'LOAD_ANALAZYDATA';
export const LOAD_ANALAZYDATA_SUCCESS = 'LOAD_ANALAZYDATA_SUCCESS';
export const LOAD_ANALAZYDATA_ERROR = 'LOAD_ANALAZYDATA_ERROR';
