// 信令的types的总量
export const LOAD_SIGNCOUNT = 'LOAD_SIGNCOUNT';
export const LOAD_SIGNCOUNT_SUCCESS = 'LOAD_SIGNCOUNT_SUCCESS';
export const LOAD_SIGNCOUNT_ERROR = 'LOAD_SIGNCOUNT_ERROR';

// 数据清洗的数据
export const LOAD_DATACLEAN = 'LOAD_DATACLEAN';
export const LOAD_DATACLEAN_SUCCESS = 'LOAD_DATACLEAN_SUCCESS'
export const LOAD_DATACLEAN_ERROR = 'LOAD_DATACLEAN_ERROR';
