//短信文种
export const LOADING_SMSLANGUAGETOP='LOADING_SMS_LANGUAGETOP';
export const LOADING_SMSLANGUAGETOP_SUCCESS='LOADING_SMS_LANGUAGETOP_SUCCESS';
export const LOADING_SMSLANGUAGETOP_ERROR='LOADING_SMS_LANGUAGETOP_ERROR';

//公众短信频次
export const LOADING_APPRECEIVEFREQUENCY='LOADING_APP_RECEIVE_FREQUENCY' 
export const LOADING_APPRECEIVEFREQUENCY_SUCCESS='LOADING_APP_RECEIVE_FREQUENCY_SUCCESS' 
export const LOADING_APPRECEIVEFREQUENCY_ERROR='LOADING_APP_RECEIVE_FREQUENCY_ERROR' 

//APP命中号码
export const LOADING_APPCONTAINSTARGETMES='LOADING_APP_CONTAINS_TARGET'
export const LOADING_APPCONTAINSTARGETMES_SUCCESS='LOADING_APP_CONTAINS_TARGET_SUCCESS'
export const LOADING_APPCONTAINSTARGETMES_ERROR='LOADING_APP_CONTAINS_TARGET_ERROR'
