//定义信令拓扑的三个查询状态   actiontypes
export const LOAD_SIGNTOPOLOGY = 'LOAD_TOPOLOGY';
export const LOAD_SIGNTOPOLOGY_SUCCESS = 'LOAD_TOPOLOGY_SUCCESS';
export const LOAD_SIGNTOPOLOGY_ERROR = 'LOAD_TOPOLOGY_ERROR';


// 定义信令基本信息数据状态
export const LOAD_SIGNBASICSTABLE = "LOAD_SIGNBASICSTABLE";
export const LOAD_SIGNBASICSTABLE_SUCCESS = 'LOAD_SIGNBASICSTABLE_SUCCESS';
export const LOAD_SIGNBASICSTABLE_ERROR = 'LOAD_SIGNBASICSTABLE_ERROR';
