export const SEARCHWAY='CHANGE_SEARCHWAY';

export const LOADING_MIDDLEPERSON = 'LOADING_MIDDLEPERSON';
export const LOADING_MIDDLEPERSON_SUCCESS = 'LOADING_MIDDLEPERSON_SUCCESS';
export const LOADING_MIDDLEPERSON_ERROR = 'LOADING_MIDDLEPERSON_ERROR';

export const LOADING_TARGETLIST = 'LOADING_TARGETLIST';
export const LOADING_TARGETLIST_SUCCESS = 'LOADING_TARGETLIST_SUCCESS';
export const LOADING_TARGETLIST_ERROR = 'LOADING_TARGETLIST_ERROR';

